spring:
  main:
    allow-circular-references: true
  token:
    expiration: 30
    assignatureKey: bHVjYXNsaW1h
  application:
    name: University Project
  profiles:
    active: local
  datasource:
    username: root
    password: 93255923
    url: jdbc:mysql://localhost:3306/db_university_project
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    server:
      port: 9191
